pipeline:
  maas:
    enabled: false

  ocr_api:
    api_host: glmocr-vllm
    api_port: 8000
    model: GLM-OCR
    api_path: /v1/chat/completions
    api_mode: openai
    connect_timeout: 30
    request_timeout: 300

  page_loader:
    max_tokens: 4096
    temperature: 0.0


  result_formatter:
    output_format: both

  layout:
    model_dir: PaddlePaddle/PP-DocLayoutV3_safetensors
    device: cpu
